### ISSUE TITLE
Add RequireComponent for RagonBehaviour

### ISSUE THREAD

**Issue by OlegDzhuraev** [edmand46/Ragon-Unity-SDK#22]
**RagonBehaviour** scripts can not work without **RagonEntity**, so it looks like a good idea to add **RagonEntity** automatically on object, when this object has some **RagonBehaviour**-deriven component.

What I suggest is to add an attribute:
```cs
[RequireComponent(typeof(RagonEntity))]
```
above **RagonBehaviour** class.

**Comment by edmand46** [comment]
Thx for your attention, but RagonBehaviour can be a nested component
