### ISSUE TITLE
RagonVector3 default constructor presicion value is too high

### ISSUE THREAD

**Issue by OlegDzhuraev** [edmand46/Ragon-Unity-SDK#28]
In one of **RagonVector3** constructors, precision is set to **0.1f**, which looks too high because of a huge data loss in case of default world size.
In another constructor of **RagonVector3** precision is set to **0.01f**, that looks more correct for a default value. 
I think, these values should be same in all constructors. :)

**Comment by edmand46** [comment]
Will be fixed in next release, thx for report!
