### ISSUE TITLE
Wrong entity id and entity type received in OnEntityCreate method

### ISSUE THREAD

**Issue by OlegDzhuraev** [edmand46/Ragon-Unity-SDK#3]
**How to reproduce:**
1. Connect to the server from the first client, and create entity when he has connected.
2. Connect from the second client. You will receive 0 as **entityId** instead of actual id. And real entity id as **entityType** instead of entity type.

Next call of **OnEntityCreate** method has correct **entityId** and **entityType**.

Also possible that this is a server-side issue.

**Comment by edmand46** [comment]
Is servers side issue, yep, fixed
